### ISSUE TITLE
Level 14 with 9 instructions

### ISSUE THREAD

**Issue by felipeyanez** [haan/Lightbot#3]
Hi @haan, my kids and I found a solution for level 14 using 9 instructions. Thanks for developing this app, we're having lots of fun!

<img width="986" alt="L14_9" src="https://github.com/haan/Lightbot/assets/3996991/71ac729c-5e1f-42a8-99f8-75464d6327f4">

**Comment by haan** [comment]
Hello @felipeyanez,

that is such a great solution! Congratulations to you and your kids. Thanks for the kind words, it was a lot of fun to develop and we regularly use it in school to introduce programming logic.

I replaced my solution with yours and mentioned you. Thanks a lot!

**Comment by haan** [comment]
@felipeyanez: would your kids like to design their own level that I would put into the game as level 15?

**Comment by felipeyanez** [comment]
That sounds awesome, they're super excited! This weekend is a bit busy for us, but I'd get back to you when they've something to share. Thx!

**Comment by felipeyanez** [comment]
Hi Laurent, the kids got something neat to share! Attached, you'll find a sketch of a pyramid they've envisioned as a new level. One of them took the responsibility of creating the top view, while the other focused on the side view. We're also suggesting a potential solution (assuming no errors 😄). Please take a look and let us know your thoughts. Thank you!

<img width="1031" alt="lightbot_level15" src="https://github.com/haan/Lightbot/assets/3996991/1c054ed9-20aa-45d7-9567-7e6578b5f12a">

**Comment by haan** [comment]
Hi @felipeyanez ,

I added level 15 and mentioned your kids beneath the game. I didn't change anything to the achievements and I don't have resources with versioning numbers so a cache-refresh is needed to actually see the level.

Thanks a lot to you and your kids.

**Comment by felipeyanez** [comment]
Laurent, I want to express my sincere gratitude for your support and kindness. Seeing my kids' excitement upon discovering level 15 today before school was truly heartwarming. The acknowledgment you included for them was beyond their wildest dreams. Your app has not only brought joy but also inspired their creativity and curiosity. Thank you for everything you've done.
